name: hate_watch
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_gradient_animation_text: ^1.0.2
  flutter_popup: ^3.3.4
  flutter_form_builder: ^9.7.0
  pixelarticons: ^0.4.0
  shared_preferences: ^2.5.3
  http: ^1.4.0
  cached_network_image: ^3.4.1
  share_plus: ^11.0.0
  loading_indicator: ^3.1.1
  loading_animation_widget: ^1.3.0
  flutter_easyloading: ^3.0.5
  quickalert: ^1.1.0
  alert_info: ^0.0.3
  tutorial_coach_mark: ^1.3.0
  sidebarx: ^0.17.1
  auto_size_text: ^3.0.0
  intl: ^0.19.0
  bcrypt: ^1.1.3

  #animations 
  pretty_animated_buttons: ^0.0.2
  card_loading: ^0.3.2
  animated_text_lerp: ^2.0.0
  typewritertext: ^3.0.9
  animate_do: ^4.2.0
  zo_animated_border: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  fonts:
    - family : Jersey
      fonts:
      - asset: ./asset/font/Jersey15-Regular.ttf